In [1]:
import numpy as np
import open3d as o3d

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
pcd = o3d.io.read_point_cloud("../data/truck/model.ply")

In [3]:
pcd

PointCloud with 136029 points.

In [5]:
np.asarray(pcd.colors)

array([[0.00000000e+00, 4.41124517e-05, 3.65788738e-04],
       [6.86584559e-04, 9.38655115e-04, 1.41200388e-03],
       [0.00000000e+00, 0.00000000e+00, 1.30521521e-04],
       ...,
       [0.00000000e+00, 7.17168754e-04, 1.28622452e-03],
       [1.83394931e-04, 4.72356847e-04, 8.04081209e-04],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [70]:
# pcd_ww_outliers_indx = (pcd.remove_statistical_outlier(nb_neighbors=50, std_ratio=0.5))

In [87]:
pcd_ww_outliers_indx = pcd.remove_radius_outlier(nb_points=2, radius=0.2)

In [88]:
pcd_ww_outliers = pcd.select_by_index(pcd_ww_outliers_indx[1])

In [89]:
pcd_ww_outliers

PointCloud with 125677 points.

In [90]:
points = np.asarray(pcd_ww_outliers.points)

In [91]:
np.max(points, axis=0), np.min(points, axis=0)

(array([0.16006318, 0.19330901, 0.37243918]),
 array([-0.22374588, -0.18138918, -0.00429772]))

In [92]:
o3d.visualization.draw_geometries([pcd_ww_outliers])

In [93]:
o3d.io.write_point_cloud("../data/small_city_road_outside-d2x/sparse/filtered_sparse.ply", pcd_ww_outliers)

True