In [10]:
import pycolmap
from src.geometry.point_transformation import get_points_xyz

In [11]:
recon = pycolmap.Reconstruction("../data/DRON 1/c7_dron_n_ground/sparse")

In [12]:
print(recon.num_images())

477


In [9]:
recon.images

{76: Image(image_id=76, camera_id=73, name="0033 (3).jpg", triangulated=4511/13501),
 395: Image(image_id=395, camera_id=394, name="0162 (2).jpg", triangulated=272/12230),
 12: Image(image_id=12, camera_id=12, name="0006 (3).jpg", triangulated=4292/13504),
 68: Image(image_id=68, camera_id=67, name="0031 (3).jpg", triangulated=4652/13408),
 387: Image(image_id=387, camera_id=387, name="0158.jpg", triangulated=264/14862),
 461: Image(image_id=461, camera_id=465, name="0193 (2).jpg", triangulated=2232/6824),
 397: Image(image_id=397, camera_id=396, name="0163 (2).jpg", triangulated=240/11639),
 479: Image(image_id=479, camera_id=480, name="0205.jpg", triangulated=1814/9601),
 415: Image(image_id=415, camera_id=415, name="0170 (2).jpg", triangulated=237/11523),
 407: Image(image_id=407, camera_id=408, name="0168 (2).jpg", triangulated=209/10539),
 8: Image(image_id=8, camera_id=2, name="0001 (3).jpg", triangulated=4499/12806),
 401: Image(image_id=401, camera_id=403, name="0166 (2).jpg", 

In [9]:
recon.num_points3D()

123386

In [10]:
recon = pycolmap.Reconstruction("../data/DRON 1/c7/sparse")

In [11]:
recon.num_points3D()

33361

In [7]:
points = get_points_xyz(recon)

In [8]:
points

array([[-0.03459682, -0.00030875,  0.17462507],
       [-0.03459682, -0.00030875,  0.17462507],
       [-0.03459682, -0.00030875,  0.17462507],
       ...,
       [-0.03459682, -0.00030875,  0.17462507],
       [-0.03459682, -0.00030875,  0.17462507],
       [-0.03459682, -0.00030875,  0.17462507]])

In [10]:
import numpy as np 

np.max(points, axis=0)

array([6.04585395e+54, 1.54434116e+57, 7.14066829e+57])

In [11]:
np.min(points, axis=0)

array([-1.78972143e+57, -1.59353409e+53, -1.03775790e+55])

In [ ]:
recon.delete_point3D()

In [ ]:
recon.write()